name: Release

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - pre-release
      releaseTag:
        description: 'Specify the Github Tag to build and release'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.releaseTag }}

      - name: Git origin branch
        run: |
          TAG_COMMIT=$(git rev-list -n 1 ${{ inputs.releaseTag }})
          echo "ORIGIN_BRANCH=$(git branch -r --contains ${TAG_COMMIT} | grep -e '->' | awk '{ print $3}')" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
            node-version: latest
      - name: NPM Install
        run: npm install
      
      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Build Extension
        if: ${{ inputs.buildType != 'release' }}
        run: |
          npm run build
          echo "EXTENSION_LOCATION=$(ls ${GITHUB_WORKSPACE}/*.vsix)" >> $GITHUB_ENV

      - name: Build Pre-Release Extension
        if: ${{ inputs.buildType != 'pre-release' }}
        run: |
          npm run build-prerelease
          echo "EXTENSION_LOCATION=$(ls ${GITHUB_WORKSPACE}/*.vsix)" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v2
        with:
          name: oc-sdk-extension
          path: ${{ env.EXTENSION_LOCATION }}
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.releaseTag }}

      - name: Create release
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: ${{ inputs.releaseTag }},
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: ${{ inputs.releaseTag }},
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }
        
      - uses: actions/download-artifact@v2
        with:
          name: oc-sdk-extension
          path: ~/download/extension

      - name: Upload Extension to GitHub
        run: |
          gh release upload ${{ inputs.releaseTag }} ~/download/extension/$(ls ~/download/extension)
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

